#list of questions and their multi-choice if applicable

SHORT_QUESTIONS = {
    "result id"                                                                                                        : "id",
    "device name"                                                                                                      : "device",
    "surveyed date"                                                                                                    : "date",
    "surveyed time"                                                                                                    : "time",
    "surveyed end date"                                                                                                : "end",
    "q1. please enter your house address and a landmark"                                                               : "q1",
    "q2. please enter the name of the area"                                                                            : "q2",
    "q3. first name"                                                                                                   : "q3",
    "q4. last name"                                                                                                    : "q4",
    "q5. husband or father's name"                                                                                     : "q5",
    "q6. age in complete years"                                                                                        : "q6",
    "q7. marital status"                                                                                               : "q7",
    "q8. occupation"                                                                                                   : "q8",
    "q9. highest level of education"                                                                                   : "q9",
    "q10. woman's religion"                                                                                            : "q10",
    "q11. what languages do you speak?"                                                                                : "q11",
    "q12. can you read and write?"                                                                                     : "q12",
    "q13. do you own a mobile phone?"                                                                                  : "q13",
    "q14. does someone in your household own a mobile phone?"                                                          : "q14",
    "q15. who owns the mobile phone you use?"                                                                          : "q15",
    "q16. please share the mobile number"                                                                              : "q16",
    "q17. what is your individual income per day on average?"                                                          : "q17",
    "q18. how many people live in your household right now?"                                                           : "q18",
    "q19. what is your household income on average per day?"                                                           : "q19",
    "q20. how many children do you have that are alive?"                                                               : "q20",
    "q21. are you currently pregnant"                                                                                  : "q21",
    "q22. how many months pregnant are you?"                                                                           : "q22",
    "q23. have you received prenatal care during this pregnancy at a facility?"                                        : "q23",
    "q24. how many prenatal care visits have you completed in total during this pregnancy?"                            : "q24",
    "q25. how many months pregnant were you when you first received prenatal care?"                                    : "q25",
    "q26. how many months pregnant were you when you last received prenatal care?"                                     : "q26",
    "q27. what was the date on which you last received prenatal care?"                                                 : "q27",
    "q28. which one of the following services did you last go to the facility for in the past two years?"              : "q28",
    "q29. if you did not go to the health center for either reason above, why did you last go the health center?"      : "q29",
    "q30. when did you last go to the health center?"                                                                  : "q30",
    "q31. when did the doctor ask you to return to the health center?"                                                 : "q31",
    "q32. what was the name of the health facility you last went to?"                                                  : "q32",
    "q33. what the address of this health center?"                                                                     : "q33",
    "q34. how far is this facility from your home in km?"                                                              : "q34",
    "q35. what type of facility is this?"                                                                              : "q35",
    "q36. why did you decide to go to this health facility"                                                            : "q36",
    "q37. was a provider present when you arrived at the facility?"                                                    : "q37",
    "q38. how many minutes did you spend with the doctor?"                                                             : "q38",
    "q39. how many minutes did you spend taking tests?"                                                                : "q39",
    "q40. how many minutes did you wait in total?"                                                                     : "q40",
    "q41. was this waiting time:"                                                                                      : "q41",
    "q42. what type of provider did you see for the consultation?"                                                     : "q42",
    "q43. what was the provider's gender?"                                                                             : "q43",
    "q44. how did the provider treat you?"                                                                             : "q44",
    "q45. did he/she address all of your issues?"                                                                      : "q45",
    "q46. did the provider explain what he/she was doing during the check up?"                                         : "q46",
    "q47. did you pay any fee for your services?"                                                                      : "q47",
    "q48. how much did you pay for the consultation?"                                                                  : "q48",
    "q49. did you receive diagnostic tests?"                                                                           : "q49",
    "q50. did you receive diagnostic tests at this facility?"                                                          : "q50",
    "q51. how much did you pay for the diagnostic tests?"                                                              : "q51",
    "q52. did you receive scanning?"                                                                                   : "q52",
    "q53. did you receive scanning at this facility?"                                                                  : "q53",
    "q54. how much did you pay for scanning?"                                                                          : "q54",
    "q55. did you receive other services?"                                                                             : "q55",
    "q56. what service did you receive?"                                                                               : "q56",
    "q57. how much did you pay for the other service?"                                                                 : "q57",
    "q58. in total, how much did you pay for the services you received at this facility only?"                         : "q58",
    "q59. was the cost:"                                                                                               : "q59",
    "q60. how much did you pay in bribes for services you received?"                                                   : "q60",
    "q61. did you have privacy during the exam?"                                                                       : "q61",
    "q62. were you satisfied with the cleanliness of the facility?"                                                    : "q62",
    "q63. how would you rate your overall experience?"                                                                 : "q63",
    "q64. what did you like about the services?"                                                                       : "q64",
    "q65. what can be improved at this facility?"                                                                      : "q65",
    "q66. are you aware of facilities other than this one in your area?"                                               : "q66",
    "q67. how many other facilities?"                                                                                  : "q67",
    "q68. do you have information on the quality of these facilities?"                                                 : "q68",
    "q69. where did you get this information?"                                                                         : "q69",
    "q70. would you like more information on the different facilities and their quality in your area?"                 : "q70",
    "q71. did the last facility you received care from ask you for your feedback on the quality of care you received?" : "q71"   
}

MULTICHOICE = {
    "q7" : ['married', 'single', 'divorced', 'other', 'no response'],
    "q8" : ['daily wage laborer', 'housewife', 'own business', 'household business', 'salaried employee', 'self-employed', 'other'],
    "q9" : ['none', 'primary', 'secondary', 'intermediate', 'graduation', 'technical', 'postgraduate'],
    "q10" : ['muslim', 'hindu', 'christian', 'no response'],
    "q11" : ['telugu', 'urdu', 'hindi', 'other'],
    "q12" : ['no', 'yes'],
    "q13" : ['no', 'yes'],
    "q14" : ['no', 'yes'],
    "q15" : ['husband', 'mother', 'father', 'mother-in-law', 'father-in-law', 'child', 'brother', 'sister', 'other'],
    "q21" : ['no', 'yes', 'no response'],
    "q23" : ['no', 'yes'],
    "q28" : ['family planning', 'postpartum care before baby turns 6 weeks old'],
    "q31" : ['in less than one month', '1 month', '2 - 3 months', '4 - 5 months', '6 months', 'more than 6 months', 'did not give an exact time', 'did not ask her to return to the facility'],
    "q35" : ['private', 'government', 'ngo', 'other'],
    "q36" : ['distance from house', 'referral from friend', 'husband chose facility', 'other family member chose facility', 'heard about it in newspaper', 'heard about it on tv', 'no cost', 'health workers are present', 'female provider', 'other'],
    "q37" : ['no', 'yes'],
    "q41" : ['too long', 'reasonable', 'short'],
    "q42" : ['nurse', 'doctor', 'community health worker'],
    "q43" : ['male', 'female'],
    "q44" : ['good', 'ok', 'bad'],
    "q45" : ['no', 'yes'],
    "q46" : ['no', 'yes'],
    "q47" : ['no', 'yes, monetary', 'yes, other'],
    "q49" : ['no', 'yes'],
    "q50" : ['no', 'yes'],
    "q52" : ['no', 'yes'],
    "q53" : ['no', 'yes'],
    "q55" : ['no', 'yes'],
    "q59" : ['too much', 'reasonable', 'minimal'],
    "q61" : ['no', 'yes'],
    "q62" : ['no', 'yes'],
    "q63" : ['very good', 'good', 'ok', 'bad', 'very bad'],
    "q64" : ['doctor was good', 'facility was clean', 'i had privacy', 'fees are low', 'female provider was present', 'close to home', 'medication was effective', 'other'],
    "q65" : ['reduce the waiting time', 'reduce fees', 'doctor/nurse should treat patients better', 'there should be drinking water', 'facilities should be kept clean', 'patients should have privacy', 'nothing needs improvement', 'other'],
    "q66" : ['no', 'yes'],
    "q68" : ['no', 'yes'],
    "q69" : ['friend', 'neighbor', 'family member', 'husband', 'pamphlets', 'tv', 'newspaper', 'other'],
    "q70" : ['no', 'yes'],
    "q71" : ['no', 'yes']
}

QUANTITATIVE = ['q6', 'q17', 'q18', 'q19', 'q20', 'q22', 'q24', 'q25', 'q26',
                'q34', 'q38', 'q39', 'q40', 'q48', 'q51', 'q54', 'q57', 'q58',
                'q60', 'q67']
    